# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
  path_filters:
    - "!perl/**"
    - "!docs/**"
    - "docs/content/**/*.md"
    - "**/README.md"
    - "src/**/*.rs"
    - ".github/workflows/**"
  path_instructions:
    - path: "docs/content/**/*.md"
      instructions: "Please look for likely typos and grammatical errors."
    - path: "**/README.md"
      instructions: "Please ensure that the README is up-to-date and accurate and look for likely typos and grammatical errors."
chat:
  auto_reply: true
