name: Deploy to Cloudflare Pages
on: [push]

jobs:
  rust-docs-build:
    name: Build Rustdoc Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Rustdoc Pages
        run: cargo doc --no-deps
      - name: Upload rustdocs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-docs
          path: target/doc

  docs-build:
    needs: rust-docs-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build Hugo Pages
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.124.1"
          extended: true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"
      - name: Run Hugo
        run: |
          cd docs
          npm ci
          hugo --minify
      - name: Upload docs/public artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-docs
          path: docs/public

  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs:
      - rust-docs-build
      - docs-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-docs
          path: docs/public
      - name: Download rustdocs artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-docs
          path: docs/public/rust
      - name: Publish to Cloudflare Pages
        id: deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: symcurve
          directory: public
          workingDirectory: docs
          wranglerVersion: "3"
