name: coverage

# almost same triggers as the rust.yml
on:
  push:
    branches: ["main"]
    paths:
      - "tests/**/*.rs"
      - "src/**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["main"]
    paths:
      - "tests/**/*.rs"
      - "src/**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --follow-exec --tests --exclude-files docs --verbose --all-features --workspace --timeout 120 --post-test-delay 3 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true
