name: Rust Build/Test on Windows

# This workflow is triggered manually.  Testing on
# Windows is not as important as testing on Unix, and it takes
# a lot longer to run.
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  call-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref || github.ref }}"
      - name: Call build workflow
        uses: ./.github/workflows/rust.yml
        with:
          runner: windows-latest
