name: Rust Build/Test Base

on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Print Cargo.lock hash
        run: "echo 'Cargo.lock hash: ' ${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
